const Actiontypes = {
    LOGIN: 'LOGIN',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
    FORM_SUBMIT_SUCCESS: 'FORM_SUBMIT_SUCCESS',
    FORM_SUBMIT_FAILED: 'FORM_SUBMIT_FAILED'
}
export default Actiontypes